### ISSUE TITLE
Provide a way to add new feed via raw RSS/Atom URL 

### ISSUE THREAD

**Issue by Krazybug** [1flow/1flow#13]
It could really useful to provide a way to add a new feed subscription directly in the "content adding pane" without installing bookmarklet, extension, ...

2 options:
* Create a new field handling feeds URLs  
* Allow the search field accepting feeds URLs

(Nice when the UI is temporarly bugged or when you're not logged on your computer ;-)

**Comment by Karmak23** [comment]
RSS/Atom feed raw URLs are accepted in the import-everything area (shortcut “i i” for “import item”) since a few months, but I cannot remember when I added the feature.

Also, the import area accepts a wallabag JSON export. No OPML, though.

**Comment by Karmak23** [comment]
RSS/Atom feed raw URLs are accepted in the import-everything area (shortcut “i i” for “import item”) since a few months, but I cannot remember when I added the feature.

Also, the import area accepts a wallabag JSON export. No OPML, though.
