### ISSUE TITLE
Android app

### ISSUE THREAD

**Issue by HLFH** [1flow/1flow#33]
Hi,

It would be nice to get an Android app for 1Flow. Wallabag has one for example and it's pretty cool ;)

Thanks in advance,

**Comment by HLFH** [comment]
Le processus d'installation de 1flow a toujours été naze, ce qui s'est révélé être le problème majeur pour la croissance de la base utilisateurs.

http://linuxfr.org/nodes/101685/comments/1528833

> Excellent !!
> 
> Traduction perso. : je pourrai bientôt fusionner Selfoss (aggrégation RSS & Sociaux > https://github.com/SSilence/selfoss) et Wallabag (Read-it-Later > https://github.com/wallabag/wallabag), et ce, avec des fonctionnalités marketing de curation. Super !
> 
> Bon courage :)

4 ans après : 

- [ ] Selfoss migré vers [Nextcloud News](https://github.com/nextcloud/news) avec utilisation rare
- [ ] [Wallabag](https://github.com/wallabag/wallabag) gardé et utilisé plusieurs fois par jour
- [ ] Un truc propriétaire comme Scoop.it n'a jamais décollé et reste cantonné à un _milieu bien compris_.
- [ ] Pocket s'est fait racheté par Mozilla et sera full open source en late 2018

Le grand gagnant sera potentiellement Pocket en fin d'année, à moins que Wallabag n'évolue d'ici-là sur certains points...

**Comment by Karmak23** [comment]
Comme pour tout projet libre, tu étais cordialement invité à venir améliorer l'installeur. Quatre ans après, on attend toujours ton premier PR. Il sembles que tu préfères jouer l'inspecteur des travaux finis qui explique aux développeurs comment ils auraient du faire pour conquérir le marché et laminer la concurrence. Du bon vieux consulting non solicité. Du SPAM, quoi… 

Le problème c'est que cette « saine compétition » et ces histoires de libre marché sont pipées. C'est du flan pour étudiants en écoles de commerce sans le moindre esprit critique, qui sur le terrain pousse les gens à s'entretuer, virtuellement ou pas, pendant que les classes dominantes profitent du spectacle en détruisant la planète pour quelques dollars ou quelques utilisateurs de plus.
 
Dès le départ de 1flow, ça n'a jamais été un objectif affiché de conquérir quoi que ce soit. Bien au contraire. Merci donc, pour ton commentaire qui est non seulement jugeant (et en cela, d'une banalité affligeante puisque tu ne fais qu'ajouter à la violence sociale, qui n'avait pas besoin de ça), mais surtout complètement hors-sujet puisque tu n'as visiblement rien compris à 1flow.

**Comment by HLFH** [comment]
> Comme pour tout projet libre, tu étais cordialement invité à venir améliorer l'installeur. Quatre ans après, on attend toujours ton premier PR. Il sembles que tu préfères jouer l'inspecteur des travaux finis qui explique aux développeurs comment ils auraient du faire pour conquérir le marché et laminer la concurrence. Du consulting non-sollicité. On appelle ça du SPAM.

Ce n'est pas du consulting, c'est une déception d'utilisateur intensif, qui apprécie la curation de contenu. Je ne peux pas faire de PR sur un projet que je n'ai pas pu utiliser à cause d'un installeur patraque. Ce n'est pas du spam, je ne te propose pas de services.

> pendant que les classes dominantes profitent du spectacle
Panem et circenses, j'aime beaucoup la politique oui.

> complètement hors-sujet puisque tu n'as visiblement rien compris à 1flow
Je crois que Ploum avait évoqué ce problème. Expliquer, c'est une responsabilité partagée, ce qui a souvent été plus compliqué pour le logiciel libre et open source.
