### ISSUE TITLE
Exclude passwords from all serializers

### ISSUE THREAD

**Issue by davidbgk** [1flow/1flow#42]
I think there is a security issue to expose passwords directly via the API. E.g.: https://1flow.io/api/mailaccounts

Thoughts?

**Comment by Karmak23** [comment]
Yup, well seen.
In fact you should be getting only your mail accounts. The REST API is not filtered on your own account currently, and that's the real bug. Storing cleartext passwords for IMAP accounts is another issue, but it's already recommended in documentation to use a dedicated account for mail feeds.

**Comment by Karmak23** [comment]
this security / privacy issue is fixed in v0.104.5.

Thanks a lot for the report.

**Comment by davidbgk** [comment]
That's the moment where inheriting from your own `BaseModelViewSet` might be appropriated ;)

**Comment by Karmak23** [comment]
In fact, permissions classes [were simply completely wrong in `sparks`](https://github.com/1flow/sparks/commit/8718fda9bc3543be49bd659084ac303cc93a61ff). I must have been smoking something or misread DRF doc while implementing them.
